async func foo(n){
   if(n <= 0){
      throw new Exception('err');
   }
   await foo(n -1);
}

foo(10).join().failure(e -> e.printStackTrace());